#!/bin/bash

# Use this hook to run a build on every commit

echo ""
echo ""
echo "Jekyll test build before commit"
echo ""
echo ""

docker run --rm \
    --volume="$PWD:/srv/jekyll" \
    --volume="/tmp/jekyll-bundle-cache:/usr/local/bundle" \
    jekyll/jekyll:3 \
    jekyll build --incremental


if [[ "$?" -ne "0" ]] ; then
  echo ""
  echo ""
  echo "Jekyll build failed - can not continue"
  echo ""
  echo ""
  exit 1
fi



# Finally, check to ensure that no published posts have have "TODO: " items left, indicating unfinished posts.

# grep "TODO" "$PWD/_posts" -R
grep "TODO" "$PWD/_posts" -R &> /dev/null

if [[ "$?" -ne "1" ]] ; then
  echo ""
  echo ""
  echo "Not all published posts are complete: the following posts have \"TODO:\" in them, indicating unfinished work."
  grep "TODO:" "$PWD/_posts" -R -l | uniq
  echo ""
  echo ""
  exit 1
fi


