# Site settings
title: Sysadmin Docs
# email: benyanke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
  This is a set of documentation created during my own personal tasks 
  and work. It's primarily for my own use, but I hope it can be of 
  assistance to others.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://docs.yanke.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  benyanke

# Build settings
markdown: kramdown
# permalink: /:year/:title:output_ext
# permalink: /:categories/:title:output_ext
permalink: /:categories/:slug:output_ext

theme: jekyll-theme-slate

# TODO: Implement this
# https://stackoverflow.com/questions/17118551/generating-a-list-of-pages-not-posts-in-a-given-category
# category-list: [ZFS, KVM]
